version: "3.7"
services:
  svelte:
    tty: true
    container_name: svelte
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Seoul
    ports:
      - "57412:80"
    
